version: '3'

services:
  deploy:
    build: ./
    env_file:
      - ./.env
    volumes:
      - type: bind
        source: ${HOME}/.ssh
        target: /root/.ssh
      - type: bind
        source: ./terraform
        target: /app/terraform
